services:
  freda3d:
    build: .
    environment:
      - NODE_ENV=production
      - TOKEN=${TOKEN}
      - CLIENT_ID=${CLIENT_ID}
    restart: unless-stopped
    command: ["node", "--trace-warnings", "src/index.js"]
